"""add formation_date to kudumbashree unit

Revision ID: 4c7c247c24fe
Revises: d473d89c524b
Create Date: 2025-04-02 07:36:23.177449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7c247c24fe'
down_revision = 'd473d89c524b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kudumbashree_unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formation_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kudumbashree_unit', schema=None) as batch_op:
        batch_op.drop_column('formation_date')

    # ### end Alembic commands ###
