"""Fixed total_amount in Order model

Revision ID: 50ead3102ae4
Revises: 4c7c247c24fe
Create Date: 2025-04-04 10:45:56.691234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50ead3102ae4'
down_revision = '4c7c247c24fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_ordered', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.drop_column('order_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('payment_method')
        batch_op.drop_column('phone')
        batch_op.drop_column('date_ordered')

    # ### end Alembic commands ###
