"""add unit_id to user model

Revision ID: d473d89c524b
Revises: c7b5ad58417a
Create Date: 2025-04-02 01:48:47.824053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd473d89c524b'
down_revision = 'c7b5ad58417a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_unit', 'kudumbashree_unit', ['unit_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_unit', type_='foreignkey')
        batch_op.drop_column('unit_id')

    # ### end Alembic commands ###
